const { parseArgs, matchesComment } = require('../scripts/delete-pr-comments');
const { BrowserComment } = require('../../../lib/gitcode-sdk');

describe('delete-pr-comments helpers', () => {
  const originalArgv = process.argv;

  afterEach(() => {
    process.argv = originalArgv;
  });

  test('parseArgs parses comma-separated comment ids', () => {
    process.argv = ['node', 'delete-pr-comments.js', '--pr', '12', '--comment-ids', '1,2,3', '--yes'];

    expect(parseArgs()).toEqual({
      prNumber: 12,
      commentIds: ['1', '2', '3'],
      allAi: false,
      bodyIncludes: null,
      uiAuth: false,
      yes: true
    });
  });

  test('matches explicit comment ids', () => {
    expect(matchesComment(
      { id: 42, body: 'hello' },
      { commentIds: ['42'], allAi: false, bodyIncludes: null }
    )).toBe(true);
  });

  test('matches ai comments', () => {
    expect(matchesComment(
      { id: 1, body: 'review\n\n---\ngenerated by ai@claude' },
      { commentIds: [], allAi: true, bodyIncludes: null }
    )).toBe(true);
  });

  test('matches body substring', () => {
    expect(matchesComment(
      { id: 1, body: 'please delete this comment' },
      { commentIds: [], allAi: false, bodyIncludes: 'delete this' }
    )).toBe(true);
  });

  test('BrowserComment deletes via internal discussion note endpoint', async () => {
    const browserComment = new BrowserComment({
      gitcode: {
        owner: 'openeuler',
        repo: 'vla-factory',
        token: 'token'
      }
    });
    const calls = [];
    browserComment._deleteInternal = async (path, token, prNumber) => {
      calls.push({ path, token, prNumber });
      return { statusCode: 204, data: '' };
    };

    const result = await browserComment.deletePRCommentWithToken(
      4,
      { id: 178449525, discussion_id: 'abc123' },
      'xauth'
    );

    expect(result.ok).toBe(true);
    expect(calls[0]).toEqual({
      path: '/issuepr/api/v1/projects/openeuler%2Fvla-factory/merge_requests/4/discussions/abc123/notes/178449525?repoId=openeuler%252Fvla-factory&iid=4',
      token: 'xauth',
      prNumber: 4
    });
  });
});
