class PRManager {
  constructor(gitcodeApi) {
    this.api = gitcodeApi;
  }

  async createPR(issue, fixAttempt, projectConfig) {
    const { owner, repo } = projectConfig;
    const branchName = `bot/fix-${issue.issueNumber}`;
    const title = `fix #${issue.issueNumber}: ${issue.title || 'auto-fix'}`;

    // In real pipeline: description generated by pr-description-writer agent
    const body = this._formatBody(issue, fixAttempt);

    try {
      const pr = await this.api.createPullRequest({
        title,
        body,
        head: branchName,
        base: 'master'
      });

      return {
        prNumber: pr.number,
        branch: branchName,
        issueRef: issue.issueNumber,
        status: 'created',
        owner,
        repo
      };
    } catch (e) {
      // API rejection — comment on Issue, mark blocked
      await this.api.commentOnIssue(
        issue.issueNumber,
        `bot blocked: PR creation failed, reason: ${e.message}`
      );
      return {
        prNumber: null,
        branch: branchName,
        issueRef: issue.issueNumber,
        status: 'bot-blocked',
        owner,
        repo
      };
    }
  }

  _formatBody(issue, fixAttempt) {
    let body = `## Changes\n\nFix for Issue #${issue.issueNumber}.\n\n`;
    body += `## Test Plan\n\n`;
    body += `- Reproduction test now passes\n`;
    body += `- Baseline tests: no new failures\n\n`;
    body += `Closes #${issue.issueNumber}`;
    return body;
  }
}

module.exports = { PRManager };
